-- MySQL Script generated by MySQL Workbench
-- Fri Oct 21 15:44:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema patient
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema patient
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patient` ;
USE `patient` ;

-- -----------------------------------------------------
-- Table `patient`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patient`.`patient` (
  `id` VARCHAR(20) NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `cell` VARCHAR(45) NOT NULL,
  `date_pos` DATE NULL DEFAULT NULL,
  `date_neg` DATE NULL DEFAULT NULL,
  `vax_date1` DATE NULL DEFAULT NULL,
  `vax_date2` DATE NULL DEFAULT NULL,
  `vax_date3` DATE NULL DEFAULT NULL,
  `vax_date4` DATE NULL DEFAULT NULL,
  `vax_creator1` VARCHAR(45) NULL DEFAULT NULL,
  `vax_creator2` VARCHAR(45) NULL DEFAULT NULL,
  `vax_creator3` VARCHAR(45) NULL DEFAULT NULL,
  `vax_creator4` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
